# GoReleaser configuration for pm - a Go package manager abstraction library
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
pro: true

project_name: pm

metadata:
  description: pm - Go library for abstracting package manager operations (Brew, Flatpak, Snap)
  homepage: "https://github.com/frostyard/pm"
  license: MIT
  maintainers:
    - "Brian Ketelsen <bketelsen@gmail.com>"

git:
  # Allow non-semver tags for snapshot builds
  ignore_tags:
    - continuous

snapshot:
  # Use a static version template that doesn't require parsing existing tags
  version_template: "{{ .ShortCommit }}-snapshot"

gomod:
  proxy: true

before:
  hooks:
    - go mod tidy

# For a library, we build test harness binaries but don't make them the primary deliverable
builds:
  - id: brewtest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
    main: ./cmd/brewtest/main.go
    binary: brewtest

  - id: flatpaktest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
    main: ./cmd/flatpaktest/main.go
    binary: flatpaktest

  - id: snaptest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
    main: ./cmd/snaptest/main.go
    binary: snaptest

archives:
  - id: test-harnesses
    name_template: "{{ .ProjectName }}-test-harnesses_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - cmd/brewtest/README.md
      - cmd/flatpaktest/README.md
      - cmd/snaptest/README.md


checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

# Libraries don't need package manager formats
# Remove nfpms section entirely for library releases

release:
  footer: |
    ## Go Library

    This is a Go library. To use it in your project:

    ```bash
    go get github.com/frostyard/pm@{{ .Tag }}
    ```

    The test harness binaries (brewtest, flatpaktest, snaptest) are provided as examples.

    **Full Changelog**: https://github.com/frostyard/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    _Released with [GoReleaser Pro](https://goreleaser.com/pro)!_

nightly:
  # Allows you to change the version of the generated nightly release.
  #
  # Note that some pipes require this to be semantic version compliant (nfpm,
  # for example).
  #
  # Default: `{{ incpatch .Version }}-{{ .ShortCommit }}-nightly`.
  # Templates: allowed.
  version_template: "{{ incmajor .Version }}-dev"

  # Tag name to create if publish_release is enabled.
  tag_name: dev

  # Whether to publish a release or not.
  # Only works on GitHub.
  publish_release: true

  # Whether to delete previous pre-releases for the same `tag_name` when
  # releasing.
  # This allows you to keep a single pre-release.
  keep_single_release: true